export const FETCH_FICTION_BOOKS_REQUEST = 'FETCH_FICTION_BOOKS_REQUEST'
export const FETCH_FICTION_BOOKS_SUCCESS = 'FETCH_FICTION_BOOKS_SUCCESS'
export const FETCH_FICTION_BOOKS_FAILURE = 'FETCH_FICTION_BOOKS_FAILURE'
